---
version: "3.7"
services:
  tomcat:
    image: tomcat:jre8-alpine
    volumes:
      - type: "volume"
        source: "webapps"
        target: "/usr/local/tomcat/webapps"
    restart: on-failure
    ports:
      - "8080:8080"
      - "3306:3306"
      - "33060:33060"
    networks:
      - app

  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - type: "volume"
        source: "webapps"
        target: "/usr/local/tomcat/webapps"
    restart: on-failure

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2hostdb
      MYSQL_DATABASE: shephertz
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
    webapps:
...