---
version: "3.8"
services:
  tomcat:
    image: tomcat:jre8-alpine
    volumes:
      webapps:/usr/local/tomcat/webapps
    restart: on-failure
# Don't declare depends_on because the worst that can happen before build is ready is a 404

  compile:
    build:
      context: .
      dockerfile: compile.Dockerfile
    volumes:
      webapps:/usr/local/tomcat/webapps
    restart: on-failure

volumes:
    webapps:
...