---
version: "3.7"
services:
  tomcat:
    image: tomcat:jre8-alpine
    volumes:
      - type: "volume"
        source: "webapps"
        target: "/usr/local/tomcat/webapps"
    restart: on-failure
    ports:
      - "8080:8080"
# Don't declare depends_on because the worst that can happen before build is ready is a 404

  build:
    build:
      context: .
      dockerfile: compile.Dockerfile
    volumes:
      - type: "volume"
        source: "webapps"
        target: "/usr/local/tomcat/webapps"
    restart: on-failure

volumes:
    webapps:
...