---
version: "3.7"
services:
  tomcat:
    image: tomcat:jre8-alpine
    volumes:
      - type: "volume"
        source: "webapps"
        target: "/usr/local/tomcat/webapps"
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - app

  build:
    build:
      context: .
      dockerfile: compile.Dockerfile
    volumes:
      - type: "volume"
        source: "webapps"
        target: "/usr/local/tomcat/webapps"
    restart: on-failure

  # db:
  #   image: mysql/mysql-server:latest
  #   restart: on-failure
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app

networks:
  app:
    driver: bridge

volumes:
    webapps:
...