---
version: "3.8"
services:
  tomcat:
    image: tomcat:jre8-alpine
    volumes:
      webapps:/usr/local/tomcat/webapps
    ports: 8080:8080
    restart: on-failure

  compile:
    build:
      context: .
      dockerfile: compile.Dockerfile
    volumes:
      webapps:/usr/local/tomcat/webapps
    restart: on-failure